best_model:
  hyperparameters:
    n_estimators: 100  # número de árboles
    max_depth: 6      # máxima profundidad
    learning_rate: 0.1  # tasa de aprendizaje
    gamma: 0.0  # mínimo descenso de pérdida para hacer una partición
    subsample: 0.6  # proporción de muestras para cada árbol
    colsample_bytree: 0.6  # proporción de columnas para cada árbol
    reg_lambda: 1.0  # término de regularización L2
    reg_alpha: 0.1  # término de regularización L1
  seed: 42  # la semilla



#{'colsample_bytree': 0.6, 'gamma': 0.0, 'learning_rate': 0.1, 'max_depth': 3, 'n_estimators': 100, 'reg_alpha': 0.1, 'reg_lambda': 1.0, 'subsample': 0.6}